apiVersion: v1
kind: CombinedService
spec:
  name: shirt-video-maker
  project: n8n-shirtvideo-mcp
  tags:
    - video-processing
    - ai
  
  # Build Configuration
  buildConfiguration:
    repository:
      url: https://github.com/Bzcasper/short-video-maker
      branch: main
    buildpack:
      type: dockerfile
      dockerfile: /main.Dockerfile
      buildContext: /
    
    # Build Arguments
    buildArguments: {}
    
    # Build Environment Variables
    buildEnvironment: {}
  
  # Runtime Configuration
  runtimeConfiguration:
    environment:
      - name: LOG_LEVEL
        value: debug
      - name: PEXELS_API_KEY
        value: "${PEXELS_API_KEY}"
      - name: VIDEO_CACHE_SIZE_IN_BYTES
        value: "2097152000"
      - name: DEV
        value: "false"
    
    # Networking
    ports:
      - name: http
        port: 3123
        protocol: HTTP
        public: true
    
    # Resources
    resources:
      cpu: 4000
      memory: 16384
      
    # Scaling
    replicas:
      min: 1
      max: 3
      
    # Health Checks
    healthChecks:
      - type: http
        path: /health
        port: 3123
        initialDelaySeconds: 30
        periodSeconds: 10